#!/usr/bin/env python3
"""study-coach 아침 브리핑 엔진 (0-LLM, 결정론적).

study-state.md(진도 정본, git 추적)를 읽어 오늘 요일에 맞는 '다음 미완료 항목'을
study-today.md(.claude/runtime/)로 뽑는다. 무인 cron(study-coach-cron.sh)이 호출한다.

설계 — automation-safety 준수:
- stdlib만 사용. LLM 판단 없음(어느 항목이 다음인지는 체크박스 순서로 결정론적).
- 무인 단계는 .claude/runtime/ 만 쓴다(study-today.md 생성 + study-state.md의 last_brief_date 갱신).
  durable content(KB·.claude 메커니즘)는 절대 건드리지 않는다 — 채점·계획 확장은 대화형 /study-coach review 몫.
- 날짜 멱등: last_brief_date == 오늘이면 no-op(비용 0). 두 Mac이 같은 날 켜져도 브리핑은 한 번만.
  → cron의 anacron 스탬프와 별개의 2차 멱등(브리핑 내용 자체의 하루 1회 보장).
- 요일 라우팅: 월~금 = [평일] 항목(20~40분), 토·일 = [주말] 항목(2~3시간).

사용: study-brief.py [--check|--dry-run|--force|--notify-line]
  --check       : 파일/파싱만 검증, study-today.md 미생성 (cron --check용)
  --dry-run     : study-today.md를 stdout으로만, state 미변경 (미리보기/테스트)
  --force       : last_brief_date 멱등 무시하고 재생성
  --notify-line : 사람용 요약 대신 osascript 알림용 한 줄만 출력
"""
import argparse, os, re, sys, datetime

ROOT = os.path.dirname(os.path.abspath(__file__))                    # .claude/
STATE = os.path.join(ROOT, "runtime", "study-state.md")
TODAY = os.path.join(ROOT, "runtime", "study-today.md")
LOCAL_CONF = os.path.join(ROOT, "runtime", "study-local.conf")      # gitignore, 머신별 override
WEEKDAY_KR = ["월", "화", "수", "목", "금", "토", "일"]

META_RE = re.compile(r"<!--\s*study-state\s+v\d+\s*\|(.*?)-->", re.S)
WEEK_HDR_RE = re.compile(r"^##\s+(W\d+)\b.*$")
ITEM_RE = re.compile(r"^- \[( |x)\]\s*\[(평일|주말)\]\s*(.+?)\s*$")


def parse_meta(text):
    """상단 메타 주석에서 key=value 추출. last_brief_date·repo_path 등."""
    m = META_RE.search(text)
    meta = {}
    if m:
        for kv in m.group(1).split("|"):
            if "=" in kv:
                k, v = kv.split("=", 1)
                meta[k.strip()] = v.strip()
    return meta


def resolve_repo_path(meta):
    """repo_path: 머신별 study-local.conf override > state 메타 > 기본값."""
    path = meta.get("repo_path", "~/ai-infra-lab")
    try:
        with open(LOCAL_CONF, encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line.startswith("repo_path="):
                    path = line.split("=", 1)[1].strip()
    except FileNotFoundError:
        pass
    return os.path.expanduser(path)


def next_item(text, want_tag):
    """want_tag('평일'/'주말')의 첫 미완료 `- [ ]` 항목을 (week, text, details)로 반환. 없으면 None.
    details = 항목 바로 아래 들여쓴 학습 가이드 불릿들(개념·자료·완료·막히면). 다음 항목/헤더 전까지."""
    lines = text.splitlines()
    week = "?"
    for i, line in enumerate(lines):
        hm = WEEK_HDR_RE.match(line)
        if hm:
            week = hm.group(1)
            continue
        im = ITEM_RE.match(line)
        if im and im.group(1) == " " and im.group(2) == want_tag:
            details = []
            for nxt in lines[i + 1:]:
                if not nxt.strip():
                    continue
                # 다음 체크박스 항목·헤더·비들여쓰기 라인을 만나면 이 항목 영역 끝.
                if ITEM_RE.match(nxt) or nxt.lstrip().startswith("#") or not nxt.startswith((" ", "\t")):
                    break
                details.append(nxt.strip().lstrip("-").strip())
            return week, im.group(3).strip(), details
    return None


def set_last_brief(text, date_str):
    """메타 주석의 last_brief_date= 값을 치환해 반환."""
    def repl(m):
        inner = re.sub(r"last_brief_date=[^|]*", f"last_brief_date={date_str} ", m.group(1))
        return "<!-- study-state v1 |" + inner + "-->"
    return META_RE.sub(repl, text, count=1)


def build_today(date, week, item, tag, repo_path, details=None):
    dow = WEEKDAY_KR[date.weekday()]
    budget = "평일 · 20~40분" if tag == "평일" else "주말 · 2~3시간 통합 실습"
    lines = [
        f"<!-- generated by study-brief.py | date={date.isoformat()} -->",
        f"# 오늘의 학습 — {date.isoformat()} ({dow})",
        "",
        f"## 오늘 할 것 ({budget})",
        f"**{week}** · {item}",
        "",
    ]
    if details:
        lines += ["### 학습 가이드"] + [f"- {d}" for d in details] + [""]
    if tag == "평일":
        lines += [
            "> 피곤하면 10분 대안: 어제 셀/스크립트 1개 다시 실행 + 변수 1개 바꿔 결과 비교 후 커밋. 연속성만 유지.",
            "",
        ]
    lines += [
        "## 어제 한 것 검토",
        f"`/study-coach review` 실행 → 어제 산출물(`{repo_path}`의 커밋·코드·docs/log.md)을 점검하고 진도를 체크합니다.",
        "",
        "## 세션 마감 형식",
        "```",
        "오늘 한 것:",
        "발생한 문제:",
        "해결하거나 확인한 내용:",
        "다음에 할 것:",
        "```",
        "",
    ]
    return "\n".join(lines)


def build_done_message(date):
    return "\n".join([
        f"<!-- generated by study-brief.py | date={date.isoformat()} -->",
        f"# 오늘의 학습 — {date.isoformat()}",
        "",
        "현재 구간의 미완료 항목이 없습니다. 🎉",
        "`/study-coach review`로 진도를 점검하고 다음 구간(W5~)을 일별로 상세화하세요.",
        "",
    ])


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--force", action="store_true")
    ap.add_argument("--notify-line", action="store_true")
    args = ap.parse_args()

    if not os.path.exists(STATE):
        print(f"FAIL: study-state.md not found: {STATE}", file=sys.stderr)
        return 1
    text = open(STATE, encoding="utf-8").read()
    meta = parse_meta(text)
    repo_path = resolve_repo_path(meta)

    if args.check:
        # 파싱 가능성만 검증 — 평일/주말 둘 중 하나라도 항목 구조가 읽히면 ok.
        ok = next_item(text, "평일") is not None or next_item(text, "주말") is not None \
            or "상세화 대기" in text
        print(f"[check] {'ok' if ok else 'FAIL: no parseable items'} state={STATE} repo={repo_path}")
        return 0 if ok else 1

    today = datetime.date.today()
    if not args.force and meta.get("last_brief_date") == today.isoformat():
        if args.notify_line:
            print("")  # 이미 브리핑함 — 알림 생략
        else:
            print(f"already briefed for {today.isoformat()} (use --force to regenerate)")
        return 0

    tag = "평일" if today.weekday() < 5 else "주말"
    found = next_item(text, tag)
    if not found:
        # 해당 요일 항목이 없으면 반대 태그라도 시도(주말에 평일 잔여가 있으면 그것을, 역도 동일).
        alt = next_item(text, "주말" if tag == "평일" else "평일")
        found = alt
        if found:
            tag = "주말" if tag == "평일" else "평일"

    if found:
        week, item, details = found
        content = build_today(today, week, item, tag, repo_path, details)
        notify = f"오늘 학습: {week} — {item[:48]}"
    else:
        content = build_done_message(today)
        notify = "오늘 학습: 미완료 항목 없음 — /study-coach review로 다음 구간 상세화"

    if args.dry_run:
        if args.notify_line:
            print(notify)
        else:
            print(content)
        return 0

    with open(TODAY, "w", encoding="utf-8") as f:
        f.write(content)
    # last_brief_date 갱신 → auto-commit이 두 Mac에 push. 멱등 키 역할.
    open(STATE, "w", encoding="utf-8").write(set_last_brief(text, today.isoformat()))

    print(notify if args.notify_line else f"wrote {TODAY}\n{notify}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
